[build]
  publish = "public"
  functions = "netlify/functions"
  ignore_plugins = ["neon-buildhooks"]

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
